version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gin_blogs
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: blog_user
      DB_PASSWORD: blog_password
      DB_NAME: gin_blogs
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:
