version: '3.8'

services:
  db:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306" # 将容器内的3306端口映射到主机上的3307端口
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: 123456
      DB_NAME: dbname
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:
