// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package useraction

import (
	"context"

	"github.com/yaqia77/golang-gin-demo/rpc__demo/user_group/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserCreateRequest = user.UserCreateRequest
	UserCreateesponse = user.UserCreateesponse
	UserInfoRequest   = user.UserInfoRequest
	UserInfoResponse  = user.UserInfoResponse

	UserAction interface {
		UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateesponse, error)
	}

	defaultUserAction struct {
		cli zrpc.Client
	}
)

func NewUserAction(cli zrpc.Client) UserAction {
	return &defaultUserAction{
		cli: cli,
	}
}

func (m *defaultUserAction) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateesponse, error) {
	client := user.NewUserActionClient(m.cli.Conn())
	return client.UserCreate(ctx, in, opts...)
}
