// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userinfo

import (
	"context"

	"github.com/yaqia77/golang-gin-demo/rpc__demo/user_group/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserCreateRequest = user.UserCreateRequest
	UserCreateesponse = user.UserCreateesponse
	UserInfoRequest   = user.UserInfoRequest
	UserInfoResponse  = user.UserInfoResponse

	UserInfo interface {
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultUserInfo struct {
		cli zrpc.Client
	}
)

func NewUserInfo(cli zrpc.Client) UserInfo {
	return &defaultUserInfo{
		cli: cli,
	}
}

func (m *defaultUserInfo) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserInfoClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
